create table if not exists public.commercial_agreements (
  id_commercial_agreement bigint generated by default as identity primary key,
  partner_name text not null,
  partner_type text not null,
  source_username text,
  source_platform text,
  starts_on date not null,
  ends_on date,
  status text not null default 'planned',
  agreed_amount numeric(14, 2),
  currency text not null default 'ARS',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commercial_agreements_partner_name_check
    check (char_length(trim(partner_name)) between 1 and 160),
  constraint commercial_agreements_partner_type_check
    check (partner_type in ('brand', 'supermarket', 'creator', 'other')),
  constraint commercial_agreements_source_platform_check
    check (source_platform is null or source_platform in ('Instagram', 'TikTok')),
  constraint commercial_agreements_status_check
    check (status in ('planned', 'active', 'completed', 'cancelled')),
  constraint commercial_agreements_dates_check
    check (ends_on is null or ends_on >= starts_on),
  constraint commercial_agreements_amount_check
    check (agreed_amount is null or agreed_amount >= 0),
  constraint commercial_agreements_currency_check
    check (currency ~ '^[A-Z]{3}$')
);

create index if not exists commercial_agreements_status_idx
  on public.commercial_agreements (status);

create index if not exists commercial_agreements_creator_idx
  on public.commercial_agreements (lower(source_username), source_platform)
  where source_username is not null;

alter table public.commercial_agreements enable row level security;

comment on table public.commercial_agreements is
  'Commercial agreements managed exclusively through authenticated admin edge functions.';
comment on column public.commercial_agreements.source_username is
  'Optional original content creator handle used to relate the agreement to attributed recipes.';

create or replace function public.set_commercial_agreement_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists commercial_agreements_set_updated_at
  on public.commercial_agreements;
create trigger commercial_agreements_set_updated_at
before update on public.commercial_agreements
for each row execute function public.set_commercial_agreement_updated_at();

